# Generated by Django 5.1.7 on 2026-03-27 02:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rejectedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplaceprofile',
            name='needs_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
        migrations.AddField(
            model_name='workplaceprofile',
            name='skills_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
    ]
