# Generated by Django 5.1.7 on 2026-03-27 09:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_needs_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='needs_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
    ]
