# Generated by Django 5.1.7 on 2026-03-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_needs_embedding_job_skills_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='embedding_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
